version: 1.0.{build}

branches:
  only:
  - master

clone_folder: c:\dev\gazebo-superbuild

environment:
  BOOST_LIBRARYDIR: c:\boost_1_55_0_codyco_superbuild\lib32-msvc-11.0
  BOOST_INCLUDEDIR: c:\boost_1_55_0_codyco_superbuild

install:
  - cmd: cinst wget -x86
  - cmd: cinst 7zip.commandline -x86
  
  - cmd: wget -q --no-check-certificate https://googledrive.com/host/0B9oJQYfVcguORjNZRlVkZzFUUHM -O c:\boost.zip
  
  - cmd: 7z x c:\boost.zip -oc:\ -y > nul


build:

build_script:
  - cd c:\dev\gazebo-superbuild
  - md build
  - cd build
  - cmake -G"Visual Studio 11" -DNON_INTERACTIVE_BUILD:BOOL=TRUE ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" gazebo-superbuild.sln

notifications:
  email:
  - silvio.traversaro@iit.it
